---
    - name: "Install rpm packages"
      become: true
      yum:
        name:
          - gcc
          - wget
          - unzip
          - rh-python36
          - python3-devel
          - https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
        state: installed
    - name: correct java version selected
      alternatives:
        name: java
        path: /usr/java/jdk1.8.0_202-amd64/jre/bin/java
    - name: add tomcatuser
      user:
        name: tomcat
        shell: /sbin/nologin
    - name: get_installer
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.76/bin/apache-tomcat-7.0.76.tar.gz
        dest: /tmp /
      become: yes
      become_user: root
    - name: copy
      command: cp -p /tmp/apache-tomcat-7.0.76.tar.gz/usr/local /
    - name: install
      unarchive:
        src: /usr/local/apache-tomcat-7.0.76.tar.gz
        dest: /usr/local
        remote_src: yes
      become: yes
      become_user: root
    - name: Firewall
      firewalld:
        port: 8080/tcp
        permanent: yes
        immediate: yes
        state: enabled
      become: yes
    - name: Change file ownership, group and permissions
      file:
        path: /usr/local/apache-tomcat-7.0.76
        owner: tomcat
        group: tomcat
        recurse: yes
        state: directory
    - name: make tomcat symbolic
      file:
        src: /usr/local/apache-tomcat-7.0.76
        dest: /usr/local/tomcat7
        owner: tomcat
        group: tomcat
        state: link
    - name: Create airflow services
      template:
        src: "tomcat.service"
        dest: "/etc/systemd/system/tomcat.service"
        mode: 0755
    - name: start tomcat
      systemd:
        name: tomcat.service
        state: started
        daemon_reload: yes
        enabled: yes
      become: yes