---
    - name: Install rpm packages
      become: true
      yum:
        name:
          - gcc
          - wget
          - unzip
          - python3-devel
          - java-1.8.0
        state: installed
    - name: add tomcatuser
      user:
        name: tomcat
        shell: /sbin/nologin
    - name: get_installer
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz
        dest: /tmp/
      become: yes
      become_user: root
    - name: copy
      command: cp -p /tmp/apache-tomcat-8.5.9.tar.gz /usr/local/
    - name: install
      unarchive:
        src: /usr/local/apache-tomcat-8.5.9.tar.gz
        dest: /usr/local
        remote_src: yes
      become: yes
      become_user: root
    - name: Change file ownership, group and permissions
      file:
        path: /usr/local/apache-tomcat-8.5.9
        owner: tomcat
        group: tomcat
        recurse: yes
        state: directory
    - name: make tomcat symbolic
      file:
        src: /usr/local/apache-tomcat-8.5.9
        dest: /usr/local/tomcat8
        owner: tomcat
        group: tomcat
        state: link
    - name: sample app
        get_url:
          url: https://tomcat.apache.org/tomcat-8.0-doc/appdev/sample/sample.war
          dest: /usr/local/tomcat8/webapps
          become: yes
          become_user: root
    - name: Create tomcat services
      template:
        src: "tomcat.service"
        dest: "/etc/systemd/system/tomcat.service"
        mode: 0755
    - name: start tomcat
      systemd:
        name: tomcat.service
        state: started
        daemon_reload: yes
        enabled: yes
      become: yes